/**
 * A User
 */

public class Publisher
{
	private String username;

	// Generated by Astah because of associations (???)
	// private EventNotification eventNotification;
	// private Event[] event;

	/**
	 * Uses raw data of post to create an event and send it to EventNotification
	 * class
	 */
	public String addPost(String command)
	{
		//Begin
		String BlahBlah = "";
		
		return BlahBlah;
		//End
		//return null;
	}

	public boolean addForum(String forum)
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

}
