import java.util.ArrayList;
import java.util.Scanner;

public class MainClass
{

	private static boolean firstEvent;

	private static Scanner kb;

	//Generated by Astah
	//private static Publisher[] publishers;
	
	//Begin
	private static ArrayList<Publisher> publishers;
	//End

	public static void main(String[] args)
	{
		//Begin
		kb = new Scanner(System.in);
		String command;
		
		/*
		 * Commands:
		 *		new forum,[forum name]
		 *		new post,[user name],[forum name],[thread title],[post text]
		 *		subscribe,[user name],[forum name]
		 *		unsubscribe,[user name],[forum name]
		 */
		
		while (!(command = kb.nextLine()).isEmpty())
		{
			if(command.matches("new forum,[\\S ]+"))
				newForum(command);
			else if(command.matches("new post,[\\S ]+,[\\S ]+,[\\S ]+,[\\S ]+"))
				newPost(command);
			else if(command.matches("subscribe,[\\S ]+,[\\S ]+"))
				subscribe(command);
			else if(command.matches("unsubscribe,[\\S ]+,[\\S ]+"))
				unsubscribe(command);
			//else
				//System.out.println("Command not recognized");
				
		}
		//End
	}

	private static boolean newForum(String command)
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

	private static boolean newPost(String command)
	{
		//Begin
		boolean succeeded = false;
		String[] parts = command.split("\\,");
		return succeeded;
		//End
		//return false;
	}

	private static boolean subscribe(String command)
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

	private static boolean unsubscribe(String command)
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

}
