import java.util.ArrayList;

public class Subscriber
{

	// Generated by Astah
	// private String forums[0..*];

	private String username;

	// Generated by Astah because of Associations
	// private EventNotification eventNotification;
	// private Event[] event;

	// Begin
	private ArrayList<String> forums = new ArrayList<String>();
	// End

	public boolean Notify()
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

	public boolean printOutput(Event e)
	{	
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

	/**
	 * Calls attachSubscriber, adds forum to forums attribute
	 */
	public boolean subscribe(String forum)
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

	/**
	 * Calls detachSubscriber, adds forum to forums attribute
	 */
	public boolean unsubscribe(String forum)
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

}
