import java.util.ArrayList;

public class ThreadInfo
{
	private int numPosts;
	private String forum;
	private String title;

	//Generated by Astah
	//private Post[] posts;
	//Begin
	private ArrayList<Post> posts = new ArrayList<Post>();
	//End

	/**
	 * Creates a post object, increases numPosts attribute by one, updates posts
	 * attribute
	 */
	public boolean addPost(String post)
	{
		//Begin
		boolean succeeded = false;
		
		return succeeded;
		//End
		//return false;
	}

}
